backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "public/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"
collections:
  - name: "getting-started" # Used in routes, e.g., /admin/collections/blog
    label: "Getting started" # Used in the UI
    folder: "src/00-getting-started" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{order}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name of post", name: "name", widget: "string"}
      - {label: "Short name", name: "title", widget: "string"}
      - label: "Layout"
        name: "layout"
        default: "default"
        widget: "select"
        options:
          - { label: "Default template", value: "default.twig" }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
